build: BatchGrayscale.java
	javac -cp .:../../../lib/commons-csv-1.8.jar:../../../lib/courserajava.jar  BatchGrayscale.java

run: BatchGrayscale.class
	java -Xmx3G -cp .:../../../lib/commons-csv-1.8.jar:../../../lib/courserajava.jar BatchGrayscale

clean:
	rm *.class
