build: Inversion.java
	javac -cp .:../lib/commons-csv-1.8.jar:../lib/courserajava.jar  Inversion.java

run: Inversion.class
	java -Xmx3G -cp .:../lib/commons-csv-1.8.jar:../lib/courserajava.jar Inversion

clean:
	rm *.class
