build: Weather.java
	javac -cp .:../../../lib/commons-csv-1.8.jar:../../../lib/courserajava.jar  Weather.java

run: Weather.class
	java -cp .:../../../lib/commons-csv-1.8.jar:../../../lib/courserajava.jar  Weather

clean:
	rm *.class
