build: BabyNames.java
	javac -cp .:../lib/commons-csv-1.8.jar:../lib/courserajava.jar  BabyNames.java

run: BabyNames.class
	java -cp .:../lib/commons-csv-1.8.jar:../lib/courserajava.jar  BabyNames

clean:
	rm *.class
